export const INITIALIZE_APP = "store.app.INITIALIZE_APP";
export const INITIALIZE_APP_SUCCESS = "store.app.INITIALIZE_APP_SUCCESS";

export const ONE_CALL_WEATHER_DATA_REQUEST =
  "store.app.ONE_CALL_WEATHER_DATA_REQUEST";
export const ONE_CALL_WEATHER_DATA_SUCCESS =
  "store.app.ONE_CALL_WEATHER_DATA_SUCCESS";
export const ONE_CALL_WEATHER_DATA_FAILURE =
  "store.app.ONE_CALL_WEATHER_DATA_FAILURE";

export const FIND_PLACE_REQUEST = "store.app.FIND_PLACE_REQUEST";
export const FIND_PLACE_SUCCESS = "store.app.FIND_PLACE_SUCCESS";
export const FIND_PLACE_FAILURE = "store.app.FIND_PLACE_FAILURE";
