export const INITIALIZE_APP = "store.app.INITIALIZE_APP";
export const INITIALIZE_APP_SUCCESS = "store.app.INITIALIZE_APP_SUCCESS";

export const ONE_CALL_WEATHER_DATA_REQUEST =
  "store.app.ONE_CALL_WEATHER_DATA_REQUEST";
export const ONE_CALL_WEATHER_DATA_SUCCESS =
  "store.app.ONE_CALL_WEATHER_DATA_SUCCESS";
export const ONE_CALL_WEATHER_DATA_FAILURE =
  "store.app.ONE_CALL_WEATHER_DATA_FAILURE";
